ACCEPT RUTA_EJECUCION CHAR PROMPT 'INGRESE RUTA DONDE SE ENCUENTRAN LOS SCRIPT A
EJECUTAR'
@&RUTA_EJECUCION\INSTALAR_TABLA_REFERENCIAS.sql
@&RUTA_EJECUCION\INSTALAR_TABLA_CLIENTES.sql
@&RUTA_EJECUCION\INSTALAR_TABLA_DEPARTAMENTOS.sql
@&RUTA_EJECUCION\INSTALAR_TABLA_CIUDADES.sql
@&RUTA_EJECUCION\INSTALAR_TABLA_OFICINAS.sql
@&RUTA_EJECUCION\INSTALAR_TABLA_PRODUCTOS.sql
@&RUTA_EJECUCION\INSTALAR_TABLA_CUENTAS.sql
@&RUTA_EJECUCION\INSTALAR_TABLA_CLAVES.sql
@&RUTA_EJECUCION\INSTALAR_TABLA_CLAVES_INVALIDAS.sql
@&RUTA_EJECUCION\INICIALIZACION_TABLA_REFERENCIAS.sql